version: '3'
services:
  app:
    build: .
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - MODE=loop
  listener:
    build: .
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - MODE=listener